DROP TABLE IF EXISTS movies CASCADE;

CREATE TABLE movies (
  id INTEGER PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  rating INTEGER,
  runtime INTEGER,
  genre VARCHAR(255)
);
