DROP TABLE IF EXISTS user_movies CASCADE;

CREATE TABLE user_movies (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  movie_id INTEGER REFERENCES movies(id) ON DELETE CASCADE,
  watch_list BOOLEAN NOT NULL DEFAULT TRUE,
  watched BOOLEAN NOT NULL DEFAULT FALSE,
);